# Generated by Django 6.0.3 on 2026-04-04 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Изменено"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название маркетплейса"
                    ),
                ),
                ("base_url", models.URLField(verbose_name="Базовый URL")),
            ],
            options={
                "verbose_name": "Маркетплейс",
                "verbose_name_plural": "Маркетплейсы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Изменено"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название товара"
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        max_length=255,
                        verbose_name="ID товара на маркетплейсе",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Текущая цена",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL изображения"
                    ),
                ),
                ("url", models.URLField(verbose_name="Ссылка на товар")),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_scraping.marketplace",
                        verbose_name="Маркетплейс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Searchers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Изменено"
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(2)
                        ],
                        verbose_name="Поисковый запрос",
                    ),
                ),
                (
                    "marketplaces",
                    models.ManyToManyField(
                        related_name="searches",
                        to="web_scraping.marketplace",
                        verbose_name="Маркетплейсы для поиска",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="searches",
                        to="web_scraping.product",
                        verbose_name="Найденные товары",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
